# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-15 20:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ihale', '0002_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ihale',
            name='guncelFiyat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ihale.Price'),
        ),
    ]
