# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-15 20:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ihale', '0003_auto_20190915_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ihale',
            name='guncelFiyat',
        ),
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ihale.ihale'),
        ),
    ]
