# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-15 20:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ihale', '0004_auto_20190915_2325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='price',
            new_name='guncel_fiyat',
        ),
    ]
