# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-15 20:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ihale', '0006_auto_20190915_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='ihale',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ihale.ihale'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.FloatField(default=None),
        ),
    ]
