# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-15 20:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ihale', '0008_auto_20190915_2334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='ihale_adi',
            new_name='ihaleAktif',
        ),
    ]
