# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-15 21:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ihale', '0009_auto_20190915_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='ihaleAktif',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ihale.Ihale'),
        ),
    ]
