# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-15 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ihale_sonuc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ihaleAdi', models.CharField(max_length=120)),
                ('urunAdi', models.CharField(max_length=120)),
                ('baslangicFiyati', models.FloatField(default=None)),
                ('sonFiyat', models.FloatField(default=None)),
                ('kimdeKaldi', models.CharField(max_length=20)),
            ],
        ),
    ]
