# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-16 06:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='price',
        ),
    ]
